version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: posrtgres_password
      PGPORT: 5432
    depends_on:
      - redis
      - postgres

  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - client
      - api

  postgres:
    container_name: postgres
    image: postgres:latest

  redis:
    container_name: redis
    image: redis:latest
