version: '3'

services:
  server:
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: posrtgres_password
      PGPORT: 5432

  postgres:
    container_name: postgres
    image: postgres:latest

  redis:
    container_name: redis
    image: redis:latest
    